name: Zero Click Deploy (AWS + Docker)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker build -t auto-backend ./backend
          docker build -t auto-frontend ./frontend

      - name: Deploy to AWS EC2 (Auto Sync)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd auto-motive-buddy
            git pull origin main
            docker-compose down
            docker-compose up -d --build
